tap "aws/tap"
tap "azure/draft"
tap "chef/chef"
tap "derailed/k9s"
tap "derailed/popeye"
tap "eth-p/software"
tap "github/gh"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "isacikgoz/gitin"
tap "nektos/tap"
tap "rigellute/tap"
tap "romkatv/powerlevel10k"
tap "snyk/tap"
tap "teamookla/speedtest"
tap "tilt-dev/tap"
tap "tomanthony/brews"
tap "vmware-tanzu/carvel"
tap "weaveworks/tap"
brew "readline"
brew "ansible"
brew "asciinema"
brew "glib"
brew "aws-iam-authenticator"
brew "awscli"
brew "azure-cli"
brew "bash-completion"
brew "bat"
brew "nghttp2"
brew "node"
brew "bitwarden-cli"
brew "boxes"
brew "calcurse"
brew "certbot"
brew "cfssl"
brew "clog"
brew "consul"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "docker-machine-driver-hyperkit"
brew "docker-machine-driver-xhyve"
brew "duf"
brew "dust"
brew "entr"
brew "exa"
brew "faas-cli"
brew "fd"
brew "fluxctl"
brew "fpp"
brew "fx"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-tf"
brew "glances"
brew "gnu-getopt"
brew "gnu-sed"
brew "unbound", restart_service: true
brew "gnupg"
brew "go"
brew "googler"
brew "harfbuzz"
brew "graphviz"
brew "grep"
brew "grv"
brew "gtk+3"
brew "helm"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jenv"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx"
brew "kubeseal"
brew "kustomize"
brew "lesspipe"
brew "libdvdcss"
brew "libxml2"
brew "mas"
brew "meson"
brew "micro"
brew "minikube", link: false
brew "moreutils"
brew "mtr"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "newman"
brew "nmap"
brew "nomad"
brew "nushell"
brew "nvm"
brew "oath-toolkit"
brew "octant"
brew "openjdk"
brew "openshift-cli"
brew "packer"
brew "packer-completion"
brew "peco"
brew "pipenv"
brew "podman", link: false
brew "prettyping"
brew "procs"
brew "putty"
brew "pyenv"
brew "ranger"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "shpotify"
brew "skaffold"
brew "tealdeer"
brew "tee-clc"
brew "telnet"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "tty-clock"
brew "vault"
brew "vdirsyncer", restart_service: true
brew "vim"
brew "watch"
brew "wget"
brew "wtfutil"
brew "yq"
brew "z"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "aws/tap/aws-sam-cli"
brew "azure/draft/draft"
brew "derailed/k9s/k9s"
brew "derailed/popeye/popeye"
brew "eth-p/software/bat-extras"
brew "hashicorp/tap/boundary"
brew "hashicorp/tap/waypoint"
brew "isacikgoz/gitin/gitin"
brew "nektos/tap/act"
brew "rigellute/tap/spotify-tui"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "teamookla/speedtest/speedtest"
brew "tilt-dev/tap/tilt"
brew "vmware-tanzu/carvel/imgpkg"
brew "vmware-tanzu/carvel/kapp"
brew "vmware-tanzu/carvel/kbld"
brew "vmware-tanzu/carvel/kwt"
brew "vmware-tanzu/carvel/vendir"
brew "vmware-tanzu/carvel/ytt"
brew "weaveworks/tap/eksctl"
cask "chefdk"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "hashicorp-boundary-desktop"
cask "java"
cask "latest"
cask "minikube"
cask "minishift"
cask "monitorcontrol"
cask "pocket-casts"
cask "podman"
cask "powershell"
cask "vagrant"
mas "2048 Game", id: 871033113
mas "Fotor Photo Editor", id: 503039729
mas "GarageBand", id: 682658836
mas "Harvest", id: 506189836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Kiwi for Gmail", id: 986304488
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
