wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [25, 25, 25, 25, 25, 25, 25, 25, 25]
    rows: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
    refreshInterval: 1
  mods:
    git:
      focusChar: 1
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 0
        height: 4
        width: 4
      refreshInterval: 8
      repositories:
      - "/Users/scott/dotfiles"
      - "/Users/scott/dotfiles/vim"
      - "/Users/scott/dotfiles/tmux"
      - "/Users/scott/Projects/presidio/pennsignals-azure"
      - "/Users/scott/Projects/presidio/vertex/vertex.active-directory.scripts"
    hackernews:
      focusChar: 2
      enabled: true
      storyType: top
      numberOfStories: 15
      position:
        top: 4
        left: 0
        height: 4
        width: 4
      refreshInterval: 300
    gcal:
      focusChar: 3
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "❗️"
      currentIcon: "⏳"
      displayResponseStatus: true
      email: "audioboxer217@gmail.com"
      enabled: true
      eventCount: 12
      multiCalendar: true
      position:
        top: 0
        left: 4
        height: 8
        width: 2
      refreshInterval: 300
      secretFile: "/keybase/private/kseppler/gcal_creds.json"
      showDeclined: true
      withLocation: true
    status:
      enabled: true
      position:
        top: 8
        left: 0
        height: 2
        width: 2
      refreshInterval: 1
    power:
      enabled: true
      position:
        top: 8
        left: 2
        height: 2
        width: 2
      refreshInterval: 15
    prettyweather:
      enabled: true
      city: "owasso"
      position:
        top: 8
        left: 4
        height: 2
        width: 2
      refreshInterval: 300
      unit: "c"
      view: 0
      language: "en"
