---
name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'
      - 'Dockerfile'
      - '.github/workflows/linter.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run Setup
        run: "$(curl -fsLS https://chezmoi.io/get)" -- init --one-shot --branch ${{ GITHUB_REF }} audioboxer/my_dotfiles.git 
