---
name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'
      - 'Dockerfile'
      - '.github/workflows/linter.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get Chezmoi
        run: curl -fsLS https://chezmoi.io/get -o install_chezmoi.sh

      - name: Run Setup
        run: ./install_chezmoi.sh -- init --apply --branch ${{ GITHUB_REF }} ${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}

      - name: Run Tests
        run: ./scripts/run_tests.sh