name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '.gitignore'
    - 'LICENSE'
    - 'Dockerfile'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run Setup
      run: ./setup_home.sh

    - name: Run Tests
      run: ./run_tests.sh

