---
name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - "LICENSE"
      - "Dockerfile"
      - ".github/workflows/linter.yml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Get Chezmoi
        run: curl -fsLS https://chezmoi.io/get -o install_chezmoi.sh && chmod +x install_chezmoi.sh

      - name: Run Setup
        run: "./install_chezmoi.sh -- init --apply --source=${GITHUB_WORKSPACE}"

      - name: Run Tests
        run: "./test/run_tests.sh | tee $GITHUB_STEP_SUMMARY"
