name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Lint Code Base
      uses: docker://github/super-linter:v2.1.0

    - name: Run Setup
      run: ./setup_home.sh
      
    - name: Run Tests
      run: ./run_tests.sh


