name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodule: recursive

    - name: Run Setup
      run: ./setup_home.sh
      
    - name: Run Tests
      run: ./run_tests.sh


